name: Java with Maven Docker and Kubernetes

on:
  workflow_dispatch:
env:
  DOCKER_USERNAME: ${{ vars.DOCKER_NAME }}
  DOCKER_PASSWORD: ${{ secrets.NEW_DOCKER_PASSWORD }}
  DOCKER_IMAGE: sairampitta/hunger-box
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Java JDK
      uses: actions/setup-java@v3.14.1
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean install

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: java-build
        path: target/*.jar

  Package:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v5.0.0
      with:
          name: java-build
          path: staging
      
    - name: List downloaded files
      run: ls staging

    
  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Java JDK
      uses: actions/setup-java@v3.14.1
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn test

  build-using-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Docker Login
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Docker Build
        run: |
          docker build -t $DOCKER_IMAGE:${{ github.sha }} .
          docker tag $DOCKER_IMAGE:${{ github.sha }} $DOCKER_IMAGE:latest

      - name: Run Docker
        run: docker run -d --name ecommerce-app -p 9091:9091 $DOCKER_IMAGE:latest

      - name: Push Docker Image
        run: |
          docker push $DOCKER_IMAGE:${{ github.sha }}
          docker push $DOCKER_IMAGE:latest

      - name: Setup Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Setup KinD
        uses: helm/kind-action@v1.7.0

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yml
          kubectl apply -f service.yml
          
      - name: get pods
        run:  kubectl get pods
